"""initial schema

Revision ID: b31b2c76549e
Revises: 
Create Date: 2026-06-20 13:45:14.847542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b31b2c76549e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitored_assets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scan_frequency', sa.Enum('hourly', 'daily', 'weekly', name='scanfrequency'), nullable=False),
    sa.Column('risk_threshold', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('logo_path', sa.String(length=512), nullable=True),
    sa.Column('homepage_screenshot_path', sa.String(length=512), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_assets_domain'), 'monitored_assets', ['domain'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'analyst', 'viewer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('allowed_domains',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['monitored_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'domain', name='uq_asset_allowed_domain')
    )
    op.create_table('brand_keywords',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['monitored_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'keyword', name='uq_asset_keyword')
    )
    op.create_table('discovered_domains',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('detection_type', sa.Enum('typosquatting', 'homoglyph', 'lookalike', 'extra_word', 'tld_variation', 'subdomain_abuse', 'cert_transparency', 'phishing_feed', 'cloned_page', 'brand_keyword', 'urlscan', name='detectiontype'), nullable=False),
    sa.Column('discovery_source', sa.String(length=128), nullable=False),
    sa.Column('resolves_dns', sa.Boolean(), nullable=True),
    sa.Column('is_active_website', sa.Boolean(), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('redirect_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('page_title', sa.String(length=512), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('favicon_url', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('asn', sa.String(length=64), nullable=True),
    sa.Column('asn_org', sa.String(length=255), nullable=True),
    sa.Column('hosting_provider', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('country_name', sa.String(length=128), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('became_inactive_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['monitored_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'domain', name='uq_asset_discovered_domain')
    )
    op.create_index(op.f('ix_discovered_domains_asset_id'), 'discovered_domains', ['asset_id'], unique=False)
    op.create_index(op.f('ix_discovered_domains_domain'), 'discovered_domains', ['domain'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('format', sa.Enum('html', 'pdf', 'csv', 'json', name='reportformat'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('filter_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['monitored_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_asset_id'), 'reports', ['asset_id'], unique=False)
    op.create_table('scan_jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('triggered_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', 'cancelled', name='scanjobstatus'), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('domains_discovered', sa.Integer(), nullable=True),
    sa.Column('domains_analysed', sa.Integer(), nullable=True),
    sa.Column('findings_created', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['monitored_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celery_task_id')
    )
    op.create_index(op.f('ix_scan_jobs_asset_id'), 'scan_jobs', ['asset_id'], unique=False)
    op.create_index(op.f('ix_scan_jobs_status'), 'scan_jobs', ['status'], unique=False)
    op.create_table('domain_dns_records',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('domain_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('record_type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['discovered_domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_dns_records_domain_id'), 'domain_dns_records', ['domain_id'], unique=False)
    op.create_table('domain_whois_records',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('domain_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('registrar', sa.String(length=255), nullable=True),
    sa.Column('registrar_url', sa.String(length=512), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('name_servers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('registrant_org', sa.String(length=512), nullable=True),
    sa.Column('registrant_country', sa.String(length=64), nullable=True),
    sa.Column('registrant_email', sa.String(length=255), nullable=True),
    sa.Column('privacy_protected', sa.Boolean(), nullable=True),
    sa.Column('raw_whois', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['discovered_domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id')
    )
    op.create_table('findings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('domain_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scan_job_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('detection_type', sa.Enum('typosquatting', 'homoglyph', 'lookalike', 'extra_word', 'tld_variation', 'subdomain_abuse', 'cert_transparency', 'phishing_feed', 'cloned_page', 'brand_keyword', 'urlscan', name='detectiontype'), nullable=False),
    sa.Column('discovery_source', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity'), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'under_review', 'confirmed', 'false_positive', 'takedown_requested', 'resolved', name='findingstatus'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('takedown_evidence_path', sa.String(length=512), nullable=True),
    sa.Column('assigned_to', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('reviewed_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['monitored_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['domain_id'], ['discovered_domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_asset_id'), 'findings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_findings_domain_id'), 'findings', ['domain_id'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_table('ssl_certificates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('domain_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('issuer_cn', sa.String(length=512), nullable=True),
    sa.Column('issuer_org', sa.String(length=512), nullable=True),
    sa.Column('subject_cn', sa.String(length=512), nullable=True),
    sa.Column('subject_alt_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('serial_number', sa.String(length=256), nullable=True),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('not_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('is_self_signed', sa.Boolean(), nullable=True),
    sa.Column('cert_fingerprint_sha256', sa.String(length=128), nullable=True),
    sa.Column('tls_version', sa.String(length=16), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['discovered_domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id')
    )
    op.create_table('threat_intel_matches',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('domain_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('feed_name', sa.String(length=128), nullable=False),
    sa.Column('feed_url', sa.String(length=512), nullable=True),
    sa.Column('threat_type', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['discovered_domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_intel_matches_domain_id'), 'threat_intel_matches', ['domain_id'], unique=False)
    op.create_table('webpage_snapshots',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('domain_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('screenshot_path', sa.String(length=512), nullable=True),
    sa.Column('html_path', sa.String(length=512), nullable=True),
    sa.Column('html_hash', sa.String(length=128), nullable=True),
    sa.Column('favicon_hash', sa.String(length=128), nullable=True),
    sa.Column('page_title', sa.String(length=512), nullable=True),
    sa.Column('external_scripts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('form_action_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_login_form', sa.Boolean(), nullable=True),
    sa.Column('has_credential_fields', sa.Boolean(), nullable=True),
    sa.Column('external_form_action', sa.Boolean(), nullable=True),
    sa.Column('brand_keywords_found', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['discovered_domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webpage_snapshots_domain_id'), 'webpage_snapshots', ['domain_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('finding_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('channel', sa.Enum('email', 'slack', 'teams', 'siem', name='alertchannel'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='alertstatus'), nullable=False),
    sa.Column('recipient', sa.String(length=512), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_finding_id'), 'alerts', ['finding_id'], unique=False)
    op.create_table('similarity_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('domain_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('snapshot_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('phash_score', sa.Float(), nullable=True),
    sa.Column('ahash_score', sa.Float(), nullable=True),
    sa.Column('dhash_score', sa.Float(), nullable=True),
    sa.Column('visual_similarity_score', sa.Float(), nullable=True),
    sa.Column('tfidf_score', sa.Float(), nullable=True),
    sa.Column('dom_similarity_score', sa.Float(), nullable=True),
    sa.Column('favicon_hash_match', sa.Boolean(), nullable=True),
    sa.Column('overall_similarity_score', sa.Float(), nullable=True),
    sa.Column('reference_screenshot_path', sa.String(length=512), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['discovered_domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['webpage_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_similarity_results_domain_id'), 'similarity_results', ['domain_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_similarity_results_domain_id'), table_name='similarity_results')
    op.drop_table('similarity_results')
    op.drop_index(op.f('ix_alerts_finding_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_webpage_snapshots_domain_id'), table_name='webpage_snapshots')
    op.drop_table('webpage_snapshots')
    op.drop_index(op.f('ix_threat_intel_matches_domain_id'), table_name='threat_intel_matches')
    op.drop_table('threat_intel_matches')
    op.drop_table('ssl_certificates')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_domain_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_asset_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_table('domain_whois_records')
    op.drop_index(op.f('ix_domain_dns_records_domain_id'), table_name='domain_dns_records')
    op.drop_table('domain_dns_records')
    op.drop_index(op.f('ix_scan_jobs_status'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_asset_id'), table_name='scan_jobs')
    op.drop_table('scan_jobs')
    op.drop_index(op.f('ix_reports_asset_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_discovered_domains_domain'), table_name='discovered_domains')
    op.drop_index(op.f('ix_discovered_domains_asset_id'), table_name='discovered_domains')
    op.drop_table('discovered_domains')
    op.drop_table('brand_keywords')
    op.drop_table('allowed_domains')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_monitored_assets_domain'), table_name='monitored_assets')
    op.drop_table('monitored_assets')
    # ### end Alembic commands ###
